### ISSUE TITLE
The return event of the function 'controller.step(action)'

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/robothor-challenge#10]
Excuse me, we have a question about the function 'controller.step()'.  When the agent perform the action, what will this function return if the agent collide with the environment or other objects ?  Does the function return the event with the agent state of the collision position? Or does the function return a invalid state？

**Comment by winthos** [comment]
The function will have an error return if the agent were to collide with the environment or other objects. The action will return an `errorMessage` string and `lastAction=false` in the event.metadata return if the agent were to collide with an object.

**Comment by liuxz-cs** [comment]
If the LastAction == False, will the agent move to the position of collision, or it will not perfrom the action?

**Comment by winthos** [comment]
If LastAction is false, the agent will not move to the point of collision. It will not perform any movement if it were to collide with something in its path.

**Comment by liuxz-cs** [comment]
Ok, thanks a lot.
