### ISSUE TITLE
Running without GPU or on headless system

### ISSUE THREAD

**Issue by vishsangale** [allenai/robothor-challenge#12]
Hi, I am wondering if it is possible to run the training scripts without GPU on the machine. I know it could be slow when running on the CPU. I was also trying to run the training scripts on AWS headless machines, and after downloading the data, the script does not move forward. So I was wondering if it was possible to run them on the headless system since some of the Unity stuff is needed to be installed and images are visualized while training.

Thanks.

**Comment by ekolve** [comment]
Unfortunately, this is not possible with the current release.  Its possible to do this (with Xvfb and mesa gl drivers), but it has shown to be extremely slow.  Does the AWS machine you are using have a GPU?

**Comment by vishsangale** [comment]
Thanks for your response. I do have a GPU on the AWS machine, but it is headless without XServer and unity, and I see there are rendering functions in `controller.step` and `controller.reset`. This rendering is helpful while debugging but I was wondering if we could disable them while training the model.

**Comment by ekolve** [comment]
I think the simplest option is to ensure you have an Nvidia driver loaded and run with the example_agent. You can share a volume to the docker container and write to that path from the agent. You can also look at the file robothor_challenge/__init__.py and modify that before launching the container. 

There isn't a way to render the image without an X server. This is an unfortunate requirement of Unity.
