### ISSUE TITLE
Possible Bug Report of Teleport in Ver. 2.3.4

### ISSUE THREAD

**Issue by SgtVincent** [allenai/robothor-challenge#13]
Hi! Previously, I found a possible bug of Teleport function in Ithor dataset, which has been posted in [issue](https://github.com/allenai/ai2thor/issues/371#issue-579100651) in allenai/aithor repo. 

Later I also found the same bug in Robothor dataset:
```
from ai2thor.controller import Controller

def get_state_from_evenet(event):
    x=event.metadata["agent"]["position"]["x"]
    y=event.metadata["agent"]["position"]["y"]
    z=event.metadata["agent"]["position"]["z"]
    rotation=event.metadata["agent"]["rotation"]["y"]
    horizon=event.metadata["agent"]["cameraHorizon"]
    return (x, y, z, rotation, horizon)

controller = Controller(
    scene="FloorPlan_Train1_1", gridSize=0.25,
    fieldOfView=90, cameraY=1.00)

event = controller.step(action="Teleport", x=2.50, y=1.00, z=-1.25)
print("Initial state: (x, y, z, rotation, horizon)={}".format(get_state_from_evenet(event)))
event = controller.step(action="Teleport", x=2.50, y=1.00, z=-1.00)
print("State after Teleport: (x, y, z, rotation, horizon)={}".format(get_state_from_evenet(event)))
print("Last Action Success:{}; Error Message:{}".format(
    event.metadata["lastActionSuccess"],
    event.metadata["errorMessage"]))
```
The agent is expected  to teleport to (x=2.50, y=1.00, z=-1.00), but the script outputs:

```
Initial state: (x, y, z, rotation, horizon)=(2.5, 0.9009992, -1.25, 269.999542, 0.0)
State after Teleport: (x, y, z, rotation, horizon)=(2.5, 0.9009996, -1.25, 269.999542, 0.0)
Last Action Success:True; Error Message:
```
which possibly means that the Teleport action fails while no error message returns.

Is there anyone to help out? This really affects my progress in the challenge. 

A million thanks!

**Comment by winthos** [comment]
The RoboTHOR dataset uses the same base framework as iTHOR, and as such share the same implementation of the Teleport action. I have posted a response requesting further details in your previous issue.

**Comment by SgtVincent** [comment]
It works,thanks!
