### ISSUE TITLE
Question about the hardware in the testing phase

### ISSUE THREAD

**Issue by xiaodongww** [allenai/robothor-challenge#14]
Hi! Here are two questions about the evaluation. 
- We want to know how many graphics cards our uploaded model can use and how much memory each card has during the test phase.
- Is there a time limit for making decisions for our model?

Thanks!

**Comment by ekolve** [comment]
We will use p3.2xlarge instances on AWS for evaluation.  These have a Tesla V100 with 16GB of GPU RAM and 61 GB of system RAM.  Models have 5s to respond with an action for each event.  If a response isn't received the episode will be timed out.

**Comment by xiaodongww** [comment]
Thanks！
