### ISSUE TITLE
error when installing nvidia driver using scripts/build.sh

### ISSUE THREAD

**Issue by jojo19125** [allenai/robothor-challenge#15]
I get this error message when I do:
cd robothor-challenge
./scripts/build.sh

i tried with sudo and added my user to docker group
are the links working?

```
Step 10/13 : RUN NVIDIA_VERSION=$NVIDIA_VERSION /app/install_nvidia.sh
 ---> Running in 
--2020-03-17 00:14:00--  http://us.download.nvidia.com/XFree86/Linux-x86_64/440.48.02/NVIDIA-Linux-x86_64-440.48.02.run
Resolving us.download.nvidia.com (us.download.nvidia.com)...  
Connecting to us.download.nvidia.com (us.download.nvidia.com) connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-17 00:14:00 ERROR 404: Not Found.

--2020-03-17 00:14:00--  http://ai2-vision-nvidia.s3-us-west-2.amazonaws.com/NVIDIA-Linux-x86_64-440.48.02.run
Resolving ai2-vision-nvidia.s3-us-west-2.amazonaws.com (ai2-vision-nvidia.s3-us-west-2.amazonaws.com)...
Connecting to ai2-vision-nvidia.s3-us-west-2.amazonaws.com (ai2-vision-nvidia.s3-us-west-2.amazonaws.com)... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-17 00:14:00 ERROR 403: Forbidden.
```

**Comment by ekolve** [comment]
Could you tell me how you you installed that version? Are you using a Vulkan beta driver? Would it be possible to use the latest long lived driver on your host:
https://www.nvidia.com/Download/driverResults.aspx/157462/en-us

If not I can figure a way to get the install_nvidia.sh script to work with your version if you can provide a location for the driver.

**Comment by jojo19125** [comment]
i updated nvidia-driver 440.64 
apt install nvidia-driver-440

it works now. Thanks
