### ISSUE TITLE
Some objects are not listed or name mismatch

### ISSUE THREAD

**Issue by rrwiyatn** [allenai/robothor-challenge#16]
Hi,

Just wanted to share: I found there are some objects in RoboThor scenes that are not listed in https://ai2thor.allenai.org/robothor/documentation/, and some of them also named differently. 

Examples are:
1. Remote -> RemoteControl
2. Drawer is not in list
3. Lamp is not in list
4. Fork is not in list

Thanks!

**Comment by AlvaroHG** [comment]
Hi!
Thanks for the tip, documentation is updated to include those objects.

**Comment by rrwiyatn** [comment]
Thanks!
