### ISSUE TITLE
About the submission.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/robothor-challenge#17]
Excuse me. We want to know what we need to run in submission.sh，do we need to run a python file, or just complenment the model and act method.

**Comment by ekolve** [comment]
submission.sh will be what is launched from within the docker container.  If you look at ./scripts/evaluate_train.sh you can see an example of how it will be called.  You can place your code within example_agent.py or use a different filename and place that into submission.sh.  If you have any non-python code that you want to run before your model is invoked you can place it in the lines preceeding the call to your agent.
