### ISSUE TITLE
The success judgement.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/robothor-challenge#18]
In robothor-challenge, only if the agent is within 1 meter of the target object and the object is also visible to the agent, the episode is considered to be successful. But in the code 'robothor-challenge/__init__.py', it looks like that it does not consider the distance between the agent and the target object when judging wether it is successful. So will this affect the evaluation in the robothor-challenge ?  Or we need to add the condition to the code ourselves and submit it?

**Comment by liuxz-cs** [comment]
We do not know what the function self.controller.last_event.get_object() do  and the result that the function returns.

**Comment by ekolve** [comment]
Regarding the first question about visibility distance, this is defined in the configuration and set during by the Initalize action.  You can see the value here:
https://github.com/allenai/robothor-challenge/blob/master/dataset/challenge_config.yaml#L3
This value can be modified during training if you choose, but it is fixed to the values defined in the file at evaluation time.

Regarding the ```get_object()``` method.  This comes from the ai2thor package here:

https://github.com/allenai/ai2thor/blob/master/ai2thor/server.py#L334

The structure of the dictionary that is returned from that object is documented here:

https://ai2thor.allenai.org/robothor/documentation/#object-attributes-

**Comment by liuxz-cs** [comment]
Thanks. I see the `get_object()` method. Actually, I mean, in this example, when you judge wether an episode is successful, you do not judge the distance. Because you only judge if the object is visible, and you do not judge the distance between the agent and target object after the agent perform 'Stop'.

**Comment by roozbehm** [comment]
We use distance to compute visibility.
