### ISSUE TITLE
In addition to the provided obsevations, can we use extra info in the challenge?

### ISSUE THREAD

**Issue by yiming107** [allenai/robothor-challenge#21]
Our team is interested in participating in the RoboTHOR Challenge. At runtime, in addition to the observations provided, our method would also require the wall structure, which we can extract from the 3D scan. We are wondering if it is eligible to encode this wall structure prior in the Agent class and submit to the challenge?  Thanks in advance!

**Comment by roozbehm** [comment]
Yes, it is perfectly fine to encode wall structures. However, we will not provide that information, and you need to infer that automatically.

**Comment by yiming107** [comment]
> Yes, it is perfectly fine to encode wall structures. However, we will not provide that information at test time, and you need to infer that automatically.

Thanks for letting know! We can infer the wall automatically using the 3d scan of the environmen. Will the 3D scan or 3D reconstruction be provided for the testing scenes?

**Comment by roozbehm** [comment]
No, they are not provided at test time.
