### ISSUE TITLE
Agent has access to RGB or RGBD observation?

### ISSUE THREAD

**Issue by Dhiraj100892** [allenai/robothor-challenge#22]
On the  [Embodied AI workshop webpage](https://embodied-ai.org/), it is mentioned that RoboTHOR challenge has access to RGBD observation. However in the [code](https://github.com/allenai/robothor-challenge/blob/78730cad617fd9106130dfc2b4119c4724443565/robothor_challenge/__init__.py#L113) only RGB observation has been provided to agent.

**Comment by ekolve** [comment]
I have just pushed a change https://github.com/allenai/robothor-challenge/commit/f052b754c347ee6898ecbed92a9c0096383a3060

You can either pull the change in or duplicate the change locally.

You will need to modify this file : https://github.com/allenai/robothor-challenge/blob/master/dataset/challenge_config.yaml
to add to the ```initialize``  section.
```yaml
    renderDepthImage: true
```

Keep in mind that RGBD is not available at evaluation time for the leaderboard.

**Comment by dhruvbatra** [comment]
> Keep in mind that RGBD is not available at evaluation time for the leaderboard.

Did something change? I thought we did agree on RGBD. Or am I misremembering?

**Comment by roozbehm** [comment]
My understanding was that these additional signals are only for training, and the evaluation is based only on RGB.

**Comment by roozbehm** [comment]
There are two tracks now: RGB and RGBD. The RGB track models have access to depth data only during training (not evaluation).
