### ISSUE TITLE
Issue with docker installation

### ISSUE THREAD

**Issue by Dhiraj100892** [allenai/robothor-challenge#25]
I have tried the `./scripts/build.sh`, however it is failing to install nvidia driver. From log it looks like it is unable to download files from the links that are mentioned in `install_nvidia.sh`. 

This is the error I received
```--2020-05-22 16:35:39--  http://us.download.nvidia.com/XFree86/Linux-x86_64/418.116.00/NVIDIA-Linux-x86_64-418.116.00.run
Resolving us.download.nvidia.com (us.download.nvidia.com)... 192.229.211.70, 2606:2800:21f:3aa:dcf:37b:1ed6:1fb
Connecting to us.download.nvidia.com (us.download.nvidia.com)|192.229.211.70|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-22 16:35:39 ERROR 404: Not Found.

--2020-05-22 16:35:39--  http://ai2-vision-nvidia.s3-us-west-2.amazonaws.com/NVIDIA-Linux-x86_64-418.116.00.run
Resolving ai2-vision-nvidia.s3-us-west-2.amazonaws.com (ai2-vision-nvidia.s3-us-west-2.amazonaws.com)... 52.218.242.105
Connecting to ai2-vision-nvidia.s3-us-west-2.amazonaws.com (ai2-vision-nvidia.s3-us-west-2.amazonaws.com)|52.218.242.105|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-05-22 16:35:39 ERROR 403: Forbidden.

```

**Comment by ekolve** [comment]
Could you tell me what platform/architecture you are on? As well as how the driver was installed if you know? The simple fix for this is to upgrade to the latest Nvidia driver, but I would like to track down the particular version you have installed and make it available in the container if possible.

**Comment by ekolve** [comment]
I was able to track down where nvidia provides these.  I have updated the install_nvidia.sh script - can you pull from master and try to run build.sh once again?

**Comment by Dhiraj100892** [comment]
I was able to build it. Thanks for help!
