### ISSUE TITLE
Issue with Success Evaluation

### ISSUE THREAD

**Issue by Dhiraj100892** [allenai/robothor-challenge#26]
Even when the `object_type` is in the view of agent and less than `1 m`  away from object, `success` is evaluated as `FALSE`

To give an example, in `scene=FloorPlan_Train1_1` and `object_type=Apple`, at  agent location `position={'x': 2.069062, 'y': 0.9009997, 'z': -2.241056}, rotation={'x': 0.0, 'y': 329.689972, 'z': 0.0}`, `apple` is completely visible and less than `1 m` away from object, still success is evaluated ([using this](https://github.com/allenai/robothor-challenge/blob/a2281a155b502f90f995d217eeaa20aa26c1427c/robothor_challenge/__init__.py#L123-L124)) as `FALSE`. For reference I have also attached agents RGB obeservation.

![test](https://user-images.githubusercontent.com/11137004/82846607-a6a11600-9eb7-11ea-8f54-6e3e9de68942.jpg)

**Comment by AlvaroHG** [comment]
Hi!
Is your agent returning the action`Stop` at the end of the episode in the `act` method of your agent? If you don't call stop success will be false by default. Let us know if this helps :)

**Comment by Dhiraj100892** [comment]
@AlvaroHG  Our agent was not calling `Stop`. Thanks for your help!
