### ISSUE TITLE
Teleporting to 60+ degree CameraHorizon

### ISSUE THREAD

**Issue by giangbang** [allenai/robothor-challenge#31]
Hi there, I'm currently using Robothor in one of my projects, and I've encountered an issue with the Teleport function that I'd like to share. When teleporting to positions with a Horizon value of approximately 60, the behavior becomes quite unpredictable. Even minor fluctuations in the Horizon values lead to unexpected changes in the agent's positions and sometimes rotation. Unfortunately, this behavior is not documented, which leads me to suspect it might be a bug.

here's a code snippet illustrating the issue:

```python
from ai2thor.controller import Controller
import random

controller = Controller(
    agentMode="locobot",
    visibilityDistance=1.5,
    scene="FloorPlan_Train1_2",
    gridSize=0.25,
    movementGaussianSigma=0,
    rotateStepDegrees=90,
    rotateGaussianSigma=0,
    renderDepthImage=False,
    renderInstanceSegmentation=False,
    width=300,
    height=300,
    fieldOfView=60
)

position = random.choice(controller.step(
    action="GetReachablePositions"
    ).metadata["actionReturn"])

rotation = {"x": 0, "y": 270, "z": 0}
horizon = 60.00001525878906   # actual value returned from the controller

metadata = controller.step(
    action="Teleport",
    position=position,
    rotation=rotation,
    horizon=horizon
).metadata["agent"]

print("Horizon:", horizon)
print(metadata["position"], metadata["rotation"], metadata["cameraHorizon"])
print('='*10)

horizon=59.9999
metadata = controller.step(
    action="Teleport",
    position=position,
    rotation=rotation,
    horizon=horizon
).metadata["agent"]

print("Horizon:", horizon)
print(metadata["position"], metadata["rotation"], metadata["cameraHorizon"])
```
output:
```
Horizon: 60.00001525878906
{'x': 2.25, 'y': 0.9009996652603149, 'z': -3.0} {'x': -0.0, 'y': 269.9995422363281, 'z': 0.0} -0.0
==========
Horizon: 59.9999
{'x': 4.0, 'y': 0.9009996652603149, 'z': -4.0} {'x': -0.0, 'y': 270.0, 'z': 0.0} 59.999908447265625
```
when the Horizon value is strictly less than 60, no unexpected results occur. However, as soon as the value exceeds 60, even a small increment, which I expect it to be clipped to 60, can lead to problematic behavior.
Im using AI2-THOR Version: 5.0.0

**Comment by apoorvkh** [comment]
In RoboTHOR, horizon values should actually be restricted to the range [-30, 30].

https://ai2thor.allenai.org/robothor/documentation/#teleport-horizon

**Comment by giangbang** [comment]
> In RoboTHOR, horizon values should actually be restricted to the range [-30, 30].

Oh sorry, I overlooked it in Robothon and confused it with Horizon in Ai2thor. 

But the robot can still `LookDown` when its horizon is 30 degrees (resulting in 60 degrees horizon), and Teleporting to < 60 is still functional so the restriction of 30 degrees is only specified in the documentation, but not enforced in the implementation.

https://github.com/allenai/robothor-challenge/assets/44130635/67c1d305-92b6-420a-acfc-287000ace6fc

**Comment by apoorvkh** [comment]
You're right, it can be possible to `LookDown` while already at 30 degrees. We simply don't guarantee functional behavior when teleporting outside the [-30, 30] range for camera horizon. If you are interested in that specific capability, I suggest opening an issue at [allenai/ai2thor](https://github.com/allenai/ai2thor) instead.
