### ISSUE TITLE
Screen goes blank after running `./scripts/evaluate_train.sh`

### ISSUE THREAD

**Issue by rrwiyatn** [allenai/robothor-challenge#6]
Hi, I followed the instruction in README but the screen of my laptop and PC both went blank after running `./scripts/evaluate_train.sh`. Have you experienced this before?

**Comment by rrwiyatn** [comment]
After commenting out `RUN NVIDIA_VERSION=$NVIDIA_VERSION /app/install_nvidia.sh` in the Dockerfile, I see the visualization (i.e., RGB image) in full screen mode and the agent running random actions.

Is there any ways to stop the evaluation or do I have to wait till it ends?

**Comment by ekolve** [comment]
Can you describe your hardware? What OS, graphics card is running on you laptop? Currently, the install only works in Linux with Nvidia GPUs.

**Comment by rrwiyatn** [comment]
I tried it both on my laptop and PC.

laptop: ubuntu 18.04.03 LTS, 16 GB RAM, i9-8950HK, Quadro P2000 (4GB)

PC: ubuntu 18.04.03 LTS, 32 GB RAM, i7-7700K, GTX 1080Ti (12GB)

**Comment by ekolve** [comment]
Are you running with the Nvidia drivers installed on your host? Or the nouveau drivers?

**Comment by ekolve** [comment]
I assume you are also already running an X server on both machines?

**Comment by rrwiyatn** [comment]
Im not using nouveau drivers, should I try nouveau instead? Yes X server already running.

**Comment by ekolve** [comment]
Can you try pulling from the repo again?  I made a change that will use your local X11 server if present from the docker container.  I was able to reproduce this and able to get a Unity window to appear on my desktop without taking over the entire terminal.  You will need to run ./scripts/build.sh before running the evaluate script.

**Comment by rrwiyatn** [comment]
Yes it works like you just described now. Thanks!
