### ISSUE TITLE
The number of target object in the scene.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/robothor-challenge#9]
Excuse me. We want to know  if the number of the target object is one in every scene? It means if there is only one target object in each scene. Does there exist several objects of the same target object type?

**Comment by winthos** [comment]
There are 13 object types that have a single guaranteed instance in all scenes. There is only a single instance of each of these types in every scene, no duplicates. These are detailed in the `Object Types` table in the documentation [you can find here.](https://ai2thor.allenai.org/robothor/documentation/)
